name: Scrape latest data

on:
  pull_request: # TODO: drop
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  scheduled:
    runs-on: python:3.13
    timeout-minutes: 15
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up env
      run: |-
        python3 -m pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        python3 dl.py > /tmp/changelog.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add ids.txt strany
        timestamp=$(date -u)
        git commit --file /tmp/changelog.txt || exit 0
        git push